# -*- coding: utf-8 -*-
"""AI study Assistant using langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ewA67Nc3s1-I3Nqclae_RcWTh8fUaP5C
"""

# ============================================================
# 📚 AI STUDY ASSISTANT
# LangChain + Google Gemini 3.6 Flash
# Google Colab - SINGLE CELL
# ============================================================

# Install packages
!pip install -q -U langchain langchain-google-genai gradio


# ------------------------------------------------------------
# IMPORTS
# ------------------------------------------------------------

import os
import gradio as gr
from getpass import getpass

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser


# ------------------------------------------------------------
# 1. ENTER GEMINI API KEY
# ------------------------------------------------------------

print("🔑 Enter your Gemini API Key")

GOOGLE_API_KEY = getpass("Gemini API Key: ")

os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY


# ------------------------------------------------------------
# 2. CREATE GEMINI MODEL
# ------------------------------------------------------------

llm = ChatGoogleGenerativeAI(
    model="gemini-3.6-flash"
)


# ------------------------------------------------------------
# 3. PROMPT TEMPLATE
# ------------------------------------------------------------

study_prompt = PromptTemplate(
    input_variables=[
        "subject",
        "topic",
        "level",
        "task"
    ],

    template="""
You are an AI Study Assistant.

Help the student learn the requested topic.

Subject: {subject}

Topic: {topic}

Student Level: {level}

Student Request: {task}


Provide the answer using the following structure:

# 📚 Topic Explanation

Give a simple and clear explanation.

# 📖 Definition

Give an easy-to-understand definition.

# 🔑 Important Concepts

Explain the main concepts using bullet points.

# 💡 Example

Give an easy real-world or programming example when appropriate.

# ⭐ Important Exam Points

List important points that a student should remember.

# 📝 Practice Questions

Create 5 practice questions.

# ❓ Multiple Choice Questions

Create 5 MCQs.

For each MCQ provide:
- Question
- Four options
- Correct answer
- Short explanation

# 🔄 Quick Revision

Give a short revision summary at the end.

Keep the explanation student-friendly and suitable
for the selected student level.
"""
)


# ------------------------------------------------------------
# 4. CREATE LANGCHAIN CHAIN
# ------------------------------------------------------------

study_chain = (
    study_prompt
    | llm
    | StrOutputParser()
)


# ------------------------------------------------------------
# 5. STUDY ASSISTANT FUNCTION
# ------------------------------------------------------------

def generate_study_material(
    subject,
    topic,
    level,
    task
):

    if not subject.strip():
        return "⚠️ Please enter a subject."

    if not topic.strip():
        return "⚠️ Please enter a topic."

    try:

        response = study_chain.invoke({

            "subject": subject,

            "topic": topic,

            "level": level,

            "task": task
        })

        return response

    except Exception as e:

        return f"""
# ❌ Error

{str(e)}

## Check the following:

1. Make sure your Gemini API key is correct.
2. Make sure the API key has access to Gemini models.
3. Make sure you have restarted the Colab runtime after installing packages.
4. Make sure your internet connection is working.
"""


# ------------------------------------------------------------
# 6. CREATE GRADIO UI
# ------------------------------------------------------------

with gr.Blocks() as demo:

    gr.Markdown(
        """
        # 📚 AI Study Assistant

        ### LangChain + Google Gemini 3.6 Flash

        Learn any subject using AI.
        """
    )


    with gr.Row():

        # LEFT SIDE
        with gr.Column():

            subject = gr.Textbox(
                label="📖 Subject",
                placeholder="Example: Computer Science"
            )


            topic = gr.Textbox(
                label="📝 Topic",
                placeholder="Example: Operating System"
            )


            level = gr.Dropdown(

                choices=[
                    "Beginner",
                    "School Student",
                    "College Student",
                    "Advanced"
                ],

                value="College Student",

                label="🎓 Student Level"
            )


            task = gr.Dropdown(

                choices=[
                    "Explain the topic",
                    "Prepare for exam",
                    "Generate notes",
                    "Generate practice questions",
                    "Quick revision"
                ],

                value="Explain the topic",

                label="🎯 What do you want?"
            )


            generate_button = gr.Button(
                "🚀 Generate Study Material"
            )


        # RIGHT SIDE
        with gr.Column():

            output = gr.Markdown(
                label="AI Response"
            )


    # --------------------------------------------------------
    # BUTTON ACTION
    # --------------------------------------------------------

    generate_button.click(

        fn=generate_study_material,

        inputs=[
            subject,
            topic,
            level,
            task
        ],

        outputs=output
    )


# ------------------------------------------------------------
# 7. LAUNCH
# ------------------------------------------------------------

demo.launch(share=True)